data_config:
  train_file: train.json
  val_file: dev.json
  test_file: dev.json
  num_proc: 2
max_input_length: 256
max_output_length: 512
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: /workspace/output
  max_steps: 200
  # needed to be fit for the dataset
  learning_rate: 5e-5
  # settings for data loading
  per_device_train_batch_size: 4
  # dataloader_num_workers: 4
  remove_unused_columns: false
  gradient_accumulation_steps: 2
  # settings for saving checkpoints
  save_strategy: steps 
  save_steps: 50
  save_safetensors: false
  save_total_limit: 10
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 16
  # 当 evaluation_strategy 与 eval_steps 给定时, training_args.do_eval 将会被设置为true
  evaluation_strategy: steps
  eval_steps: 100
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 512
  # set your absolute deepspeed path here
  # deepspeed: /workspace/ChatGLM3/finetune_demo/configs/ds_zero_3.json
  # set to true if train with cpu.
  use_cpu: false
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
